In [49]:
import pandas as pd

path = "../data/raw/games.csv"

columns = pd.read_csv(path, nrows=0).columns.tolist()

position = columns.index("DiscountDLC count")
columns[position:position + 1] = ["Discount", "DLC count"]

df = pd.read_csv(
    path,
    skiprows=1,
    names=columns
)

In [50]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 125855 entries, 0 to 125854
Data columns (total 40 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   AppID                       125855 non-null  int64
 1   Name                        125854 non-null  str
 2   Release date                125855 non-null  str
 3   Estimated owners            125855 non-null  str
 4   Peak CCU                    125855 non-null  int64
 5   Required age                125855 non-null  int64
 6   Price                       125855 non-null  float64
 7   Discount                    125855 non-null  int64
 8   DLC count                   125855 non-null  int64
 9   About the game              117393 non-null  str
 10  Supported languages         125855 non-null  str
 11  Full audio languages        125855 non-null  str
 12  Reviews                     12181 non-null   str
 13  Header image                125774 non-null  str
 14  Website                     50520 non-null   str
 15  Support url                 55295 non-null   str
 16  Support email               103225 non-null  str
 17  Windows                     125855 non-null  bool
 18  Mac                         125855 non-null  bool
 19  Linux                       125855 non-null  bool
 20  Metacritic score            125855 non-null  int64
 21  Metacritic url              4258 non-null    str
 22  User score                  125855 non-null  int64
 23  Positive                    125855 non-null  int64
 24  Negative                    125855 non-null  int64
 25  Score rank                  40 non-null      float64
 26  Achievements                125855 non-null  int64
 27  Recommendations             125855 non-null  int64
 28  Notes                       23310 non-null   str
 29  Average playtime forever    125855 non-null  int64
 30  Average playtime two weeks  125855 non-null  int64
 31  Median playtime forever     125855 non-null  int64
 32  Median playtime two weeks   125855 non-null  int64
 33  Developers                  117406 non-null  str
 34  Publishers                  116933 non-null  str
 35  Categories                  116889 non-null  str
 36  Genres                      117432 non-null  str
 37  Tags                        83353 non-null   str
 38  Screenshots                 119828 non-null  str
 39  Movies                      0 non-null       float64
dtypes: bool(3), float64(3), int64(15), str(19)
memory usage: 403.9 MB

In [51]:
df.columns

Index(['AppID', 'Name', 'Release date', 'Estimated owners', 'Peak CCU',
       'Required age', 'Price', 'Discount', 'DLC count', 'About the game',
       'Supported languages', 'Full audio languages', 'Reviews',
       'Header image', 'Website', 'Support url', 'Support email', 'Windows',
       'Mac', 'Linux', 'Metacritic score', 'Metacritic url', 'User score',
       'Positive', 'Negative', 'Score rank', 'Achievements', 'Recommendations',
       'Notes', 'Average playtime forever', 'Average playtime two weeks',
       'Median playtime forever', 'Median playtime two weeks', 'Developers',
       'Publishers', 'Categories', 'Genres', 'Tags', 'Screenshots', 'Movies'],
      dtype='str')

In [52]:
df.shape

(125855, 40)

In [53]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 125855 entries, 0 to 125854
Data columns (total 40 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   AppID                       125855 non-null  int64
 1   Name                        125854 non-null  str
 2   Release date                125855 non-null  str
 3   Estimated owners            125855 non-null  str
 4   Peak CCU                    125855 non-null  int64
 5   Required age                125855 non-null  int64
 6   Price                       125855 non-null  float64
 7   Discount                    125855 non-null  int64
 8   DLC count                   125855 non-null  int64
 9   About the game              117393 non-null  str
 10  Supported languages         125855 non-null  str
 11  Full audio languages        125855 non-null  str
 12  Reviews                     12181 non-null   str
 13  Header image                125774 non-null  str
 14  Website                     50520 non-null   str
 15  Support url                 55295 non-null   str
 16  Support email               103225 non-null  str
 17  Windows                     125855 non-null  bool
 18  Mac                         125855 non-null  bool
 19  Linux                       125855 non-null  bool
 20  Metacritic score            125855 non-null  int64
 21  Metacritic url              4258 non-null    str
 22  User score                  125855 non-null  int64
 23  Positive                    125855 non-null  int64
 24  Negative                    125855 non-null  int64
 25  Score rank                  40 non-null      float64
 26  Achievements                125855 non-null  int64
 27  Recommendations             125855 non-null  int64
 28  Notes                       23310 non-null   str
 29  Average playtime forever    125855 non-null  int64
 30  Average playtime two weeks  125855 non-null  int64
 31  Median playtime forever     125855 non-null  int64
 32  Median playtime two weeks   125855 non-null  int64
 33  Developers                  117406 non-null  str
 34  Publishers                  116933 non-null  str
 35  Categories                  116889 non-null  str
 36  Genres                      117432 non-null  str
 37  Tags                        83353 non-null   str
 38  Screenshots                 119828 non-null  str
 39  Movies                      0 non-null       float64
dtypes: bool(3), float64(3), int64(15), str(19)
memory usage: 403.9 MB

In [54]:
df.columns.tolist()

['AppID',
 'Name',
 'Release date',
 'Estimated owners',
 'Peak CCU',
 'Required age',
 'Price',
 'Discount',
 'DLC count',
 'About the game',
 'Supported languages',
 'Full audio languages',
 'Reviews',
 'Header image',
 'Website',
 'Support url',
 'Support email',
 'Windows',
 'Mac',
 'Linux',
 'Metacritic score',
 'Metacritic url',
 'User score',
 'Positive',
 'Negative',
 'Score rank',
 'Achievements',
 'Recommendations',
 'Notes',
 'Average playtime forever',
 'Average playtime two weeks',
 'Median playtime forever',
 'Median playtime two weeks',
 'Developers',
 'Publishers',
 'Categories',
 'Genres',
 'Tags',
 'Screenshots',
 'Movies']

In [55]:
df.head(3)

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,Discount,DLC count,About the game,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN

In [56]:
df.duplicated().sum()

np.int64(0)

In [57]:
for col in df.columns:
    print(col)

AppID
Name
Release date
Estimated owners
Peak CCU
Required age
Price
Discount
DLC count
About the game
Supported languages
Full audio languages
Reviews
Header image
Website
Support url
Support email
Windows
Mac
Linux
Metacritic score
Metacritic url
User score
Positive
Negative
Score rank
Achievements
Recommendations
Notes
Average playtime forever
Average playtime two weeks
Median playtime forever
Median playtime two weeks
Developers
Publishers
Categories
Genres
Tags
Screenshots
Movies

In [58]:
missing_percentage = (
    df.isnull()
      .mean()
      .mul(100)
      .round(2)
      .sort_values(ascending=False)
)

missing_percentage

Movies                        100.00
Score rank                     99.97
Metacritic url                 96.62
Reviews                        90.32
Notes                          81.48
Website                        59.86
Support url                    56.06
Tags                           33.77
Support email                  17.98
Categories                      7.12
Publishers                      7.09
About the game                  6.72
Developers                      6.71
Genres                          6.69
Screenshots                     4.79
Header image                    0.06
Negative                        0.00
Average playtime forever        0.00
Median playtime forever         0.00
Recommendations                 0.00
Achievements                    0.00
Median playtime two weeks       0.00
Average playtime two weeks      0.00
AppID                           0.00
Positive                        0.00
User score                      0.00
Name                            0.00
Linux                           0.00
Mac                             0.00
Windows                         0.00
Full audio languages            0.00
Supported languages             0.00
DLC count                       0.00
Discount                        0.00
Price                           0.00
Required age                    0.00
Peak CCU                        0.00
Estimated owners                0.00
Release date                    0.00
Metacritic score                0.00
dtype: float64

In [59]:
df.iloc[0]

AppID                                                                   2539430
Name                                                 Black Dragon Mage Playtest
Release date                                                        Aug 1, 2023
Estimated owners                                                          0 - 0
Peak CCU                                                                      0
Required age                                                                  0
Price                                                                       0.0
Discount                                                                      0
DLC count                                                                     0
About the game                                                              NaN
Supported languages                                                          []
Full audio languages                                                         []
Reviews                                                                     NaN
Header image                  https://shared.akamai.steamstatic.com/store_it...
Website                                                                     NaN
Support url                                                                 NaN
Support email                                                               NaN
Windows                                                                    True
Mac                                                                       False
Linux                                                                     False
Metacritic score                                                              0
Metacritic url                                                              NaN
User score                                                                    0
Positive                                                                      0
Negative                                                                      0
Score rank                                                                  NaN
Achievements                                                                  0
Recommendations                                                               0
Notes                                                                       NaN
Average playtime forever                                                      0
Average playtime two weeks                                                    0
Median playtime forever                                                       0
Median playtime two weeks                                                     0
Developers                                                                  NaN
Publishers                                                                  NaN
Categories                                                                  NaN
Genres                                                                      NaN
Tags                                                                        NaN
Screenshots                   https://shared.akamai.steamstatic.com/store_it...
Movies                                                                      NaN
Name: 0, dtype: object

In [60]:
df.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,Discount,DLC count,About the game,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
4,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

In [61]:
clean_df = df.copy()

In [62]:
clean_df = clean_df.drop_duplicates()

In [63]:
columns_to_keep = [
    "AppID",
    "Name",
    "About the game",
    "Genres",
    "Tags",
    "Developers",
    "Publishers",
    "Price",
    "Release date",
    "Positive",
    "Negative",
    "Recommendations",
    "Metacritic score",
    "Categories",
    "Windows",
    "Mac",
    "Linux"
]

clean_df = clean_df[columns_to_keep]

In [64]:
text_columns = [
    "About the game",
    "Genres",
    "Tags",
    "Developers",
    "Publishers",
    "Categories"
]

clean_df[text_columns] = clean_df[text_columns].fillna("")

In [65]:
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 125855 entries, 0 to 125854
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   AppID             125855 non-null  int64
 1   Name              125854 non-null  str
 2   About the game    125855 non-null  str
 3   Genres            125855 non-null  str
 4   Tags              125855 non-null  str
 5   Developers        125855 non-null  str
 6   Publishers        125855 non-null  str
 7   Price             125855 non-null  float64
 8   Release date      125855 non-null  str
 9   Positive          125855 non-null  int64
 10  Negative          125855 non-null  int64
 11  Recommendations   125855 non-null  int64
 12  Metacritic score  125855 non-null  int64
 13  Categories        125855 non-null  str
 14  Windows           125855 non-null  bool
 15  Mac               125855 non-null  bool
 16  Linux             125855 non-null  bool
dtypes: bool(3), float64(1), int64(5), str(8)
memory usage: 191.7 MB

In [66]:
clean_df.head()

,AppID,Name,About the game,Genres,Tags,Developers,Publishers,Price,Release date,Positive,Negative,Recommendations,Metacritic score,Categories,Windows,Mac,Linux
0,2539430,Black Dragon Mage Playtest,,,,,,0.00,"Aug 1, 2023",0,0,0,0,,True,False,False
1,496350,Supipara - Chapter 1 Spring Has Come!,"Springtime, April: when the cherry trees come ...",Adventure,"Adventure,Visual Novel,Anime,Cute",minori,MangaGamer,5.24,"Jul 29, 2016",252,3,231,0,"Single-player,Steam Trading Cards,Steam Cloud,...",True,False,False
2,1034400,Mystery Solitaire The Black Raven,"Immerse yourself in the most beloved, mystical...",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",Somer Games,8floor,4.99,"May 6, 2019",21,3,0,0,"Single-player,Family Sharing",True,True,False
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...","Casual,Indie,Simulation",,유진게임즈,유진게임즈,8.99,"Oct 31, 2024",0,0,0,0,"Single-player,Steam Achievements,Family Sharing",True,False,False
4,3631080,Maze Quest VR,Its not just a Maze; its a Quest! Enter the ca...,"Action,Early Access",,Reality Expanded LLC,Reality Expanded LLC,4.99,"Apr 24, 2025",0,0,0,0,"Single-player,VR Only,Steam Leaderboards,Famil...",True,False,False

In [67]:
clean_df = clean_df.dropna(subset=["AppID"])

In [68]:
clean_df["AppID"].isna().sum()

np.int64(0)

In [69]:
clean_df["Tags"] = clean_df["Tags"].str.replace(",", ", ")
clean_df["Genres"] = clean_df["Genres"].str.replace(",", ", ")
clean_df["Categories"] = clean_df["Categories"].str.replace(",", ", ")

In [70]:
clean_df["embedding_text"] = (
    clean_df["Name"] + ". " +
    clean_df["About the game"] + ". " +
    "Genres: " + clean_df["Genres"] + ". " +
    "Tags: " + clean_df["Tags"] + ". " +
    "Categories: " + clean_df["Categories"]
)

In [71]:
clean_df[["Name", "embedding_text"]].head(3)

,Name,embedding_text
0,Black Dragon Mage Playtest,Black Dragon Mage Playtest. . Genres: . Tags: ...
1,Supipara - Chapter 1 Spring Has Come!,Supipara - Chapter 1 Spring Has Come!. Springt...
2,Mystery Solitaire The Black Raven,Mystery Solitaire The Black Raven. Immerse you...

In [72]:
print(clean_df["embedding_text"].iloc[1])

Supipara - Chapter 1 Spring Has Come!. Springtime, April: when the cherry trees come into full bloom. The protagonist Yukinari Sanada has returned to his hometown in Kanagawa Prefecture, Kamakura City, for the first time in seven years, and is greeted by his older cousin Sakura Narumi (complete with maid outfit). He wanted to live in peace, but his life at the academy placed on the coastlands becomes bustling and brilliant while surrounded by a lineup of girls with booming personalities like Hotaru Amano, the sharp tongued, half-Japanese beauty, and Alice Kamishiro, the lazy witch who loves modern-science and mail-orders. Eventually, our protagonist is coaxed into joining the action committee for the academy's traditional beauty contest by his close friend. He interacts with the heroines participating in this contest who are cute but each have an idiocyncrasy or two. Fun events (with their own difficulties) pop up again and again. Your story with 'her' about smiles, peace, passion, and love, all while borrowing the power of a witch, is about to begin! 'Supipara - Alice the Magical Conductor.' is an interactive novel themed around 'dynamicism' depicted through a rallying all of the production techniques minori has accumulated to date. See expressive character portraits with moving eyes, mouths, even hair! It is quite immersive in many aspects. Also, 'Supipara' won't conclude in a single game. It will be released as several standalone episodes. Fans may freely pursue only the episodes that interest them if so desired. You could say 'it's a light novel series, and independent stories which develop their own unique personalities all in one.'. Genres: Adventure. Tags: Adventure, Visual Novel, Anime, Cute. Categories: Single-player, Steam Trading Cards, Steam Cloud, Family Sharing

In [73]:
clean_df.loc[clean_df["AppID"] == "496350", ["AppID", "Name", "Release date"]]

Empty DataFrame
Columns: [AppID, Name, Release date]
Index: []

In [74]:
clean_df.loc[clean_df["AppID"] == 496350, ["AppID", "Name", "Release date"]]

    AppID                                   Name  Release date
1  496350  Supipara - Chapter 1 Spring Has Come!  Jul 29, 2016

In [75]:
clean_df.iloc[1][["AppID", "Name", "Release date"]]

AppID                                          496350
Name            Supipara - Chapter 1 Spring Has Come!
Release date                             Jul 29, 2016
Name: 1, dtype: object

In [76]:
clean_df.reset_index().head()

,index,AppID,Name,About the game,Genres,Tags,Developers,Publishers,Price,Release date,Positive,Negative,Recommendations,Metacritic score,Categories,Windows,Mac,Linux,embedding_text
0,0,2539430,Black Dragon Mage Playtest,,,,,,0.00,"Aug 1, 2023",0,0,0,0,,True,False,False,Black Dragon Mage Playtest. . Genres: . Tags: ...
1,1,496350,Supipara - Chapter 1 Spring Has Come!,"Springtime, April: when the cherry trees come ...",Adventure,"Adventure, Visual Novel, Anime, Cute",minori,MangaGamer,5.24,"Jul 29, 2016",252,3,231,0,"Single-player, Steam Trading Cards, Steam Clou...",True,False,False,Supipara - Chapter 1 Spring Has Come!. Springt...
2,2,1034400,Mystery Solitaire The Black Raven,"Immerse yourself in the most beloved, mystical...",Casual,"Casual, Card Game, Solitaire, Puzzle, Hidden O...",Somer Games,8floor,4.99,"May 6, 2019",21,3,0,0,"Single-player, Family Sharing",True,True,False,Mystery Solitaire The Black Raven. Immerse you...
3,3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...","Casual, Indie, Simulation",,유진게임즈,유진게임즈,8.99,"Oct 31, 2024",0,0,0,0,"Single-player, Steam Achievements, Family Sharing",True,False,False,"버튜버 파라노이아 - Vtuber Paranoia. synopsis 'Hello, ..."
4,4,3631080,Maze Quest VR,Its not just a Maze; its a Quest! Enter the ca...,"Action, Early Access",,Reality Expanded LLC,Reality Expanded LLC,4.99,"Apr 24, 2025",0,0,0,0,"Single-player, VR Only, Steam Leaderboards, Fa...",True,False,False,Maze Quest VR. Its not just a Maze; its a Ques...

In [77]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [78]:
test_texts = clean_df["embedding_text"].head(5).tolist()

test_embeddings = model.encode(test_texts)

test_embeddings.shape

(5, 384)

In [79]:
test_embeddings[0][:10]

array([-0.0407057 , -0.03781202, -0.0741763 ,  0.01398312, -0.03537194,
        0.0313898 ,  0.07930134, -0.0311048 , -0.05175598, -0.053143  ],
      dtype=float32)

In [80]:
from qdrant_client import QdrantClient

client = QdrantClient("localhost", port=6333)

client.get_collections()

CollectionsResponse(collections=[CollectionDescription(name='steam_games')])

In [81]:
from qdrant_client.models import Distance, VectorParams

client.create_collection(
    collection_name="steam_games",
    vectors_config=VectorParams(
        size=384,
        distance=Distance.COSINE
    )
)

UnexpectedResponse: Unexpected Response: 409 (Conflict)
Raw response content:
b'{"status":{"error":"Wrong input: Collection `steam_games` already exists!"},"time":0.000555666}'

In [ ]:
client.get_collections()

CollectionsResponse(collections=[CollectionDescription(name='steam_games')])

In [ ]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [ ]:
sample_df = clean_df.head(10).copy()

vectors = model.encode(
    sample_df["embedding_text"].tolist(),
    show_progress_bar=True
)

vectors.shape

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

(10, 384)

In [ ]:
from qdrant_client.models import PointStruct

points = []

for i, (_, row) in enumerate(sample_df.iterrows()):
    payload = {
        "name": row["Name"],
        "genres": row["Genres"],
        "tags": row["Tags"],
        "developers": row["Developers"],
        "publishers": row["Publishers"],
        "price": row["Price"],
        "release_date": row["Release date"],
        "positive": row["Positive"],
        "negative": row["Negative"],
        "categories": row["Categories"],
    }

    points.append(
        PointStruct(
            id=i,
            vector=vectors[i].tolist(),
            payload=payload
        )
    )

In [ ]:
client.upsert(
    collection_name="steam_games",
    points=points
)

UpdateResult(operation_id=1, status=<UpdateStatus.COMPLETED: 'completed'>)

In [ ]:
client.count("steam_games")

CountResult(count=10)

In [ ]:
query = "A relaxing card game with puzzles"

query_vector = model.encode(query).tolist()

In [ ]:
results = client.query_points(
    collection_name="steam_games",
    query=query_vector,
    limit=5
)

In [ ]:
for point in results.points:
    print(point.payload["name"])
    print(point.score)
    print("-" * 50)

May 6, 2019
0.66169345
--------------------------------------------------
Apr 24, 2025
0.3631346
--------------------------------------------------
Dec 13, 2021
0.27675346
--------------------------------------------------
May 7, 2021
0.26462176
--------------------------------------------------
Feb 1, 2018
0.25787932
--------------------------------------------------

In [ ]:
clean_df[["AppID", "Name", "Release date"]].head()

                                         AppID          Name Release date
2539430             Black Dragon Mage Playtest   Aug 1, 2023        0 - 0
496350   Supipara - Chapter 1 Spring Has Come!  Jul 29, 2016    0 - 20000
1034400      Mystery Solitaire The Black Raven   May 6, 2019    0 - 20000
3292190            버튜버 파라노이아 - Vtuber Paranoia  Oct 31, 2024    0 - 20000
3631080                          Maze Quest VR  Apr 24, 2025    0 - 20000

In [ ]:
df[[
    "AppID",
    "Name",
    "Release date",
    "Price",
    "Discount",
    "DLC count"
]].head()

,AppID,Name,Release date,Price,Discount,DLC count
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0.00,0,0
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",5.24,65,0
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",4.99,0,0
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",8.99,0,1
4,3631080,Maze Quest VR,"Apr 24, 2025",4.99,0,0

In [82]:
clean_df = df.copy()

In [83]:
clean_df = df.copy()

In [84]:
clean_df = clean_df.drop_duplicates()

In [85]:
columns_to_keep = [...]
clean_df = clean_df[columns_to_keep]

KeyError: "None of [Index([Ellipsis], dtype='object')] are in the [columns]"

In [86]:
columns_to_keep = [
    "AppID",
    "Name",
    "About the game",
    "Genres",
    "Tags",
    "Developers",
    "Publishers",
    "Price",
    "Release date",
    "Positive",
    "Negative",
    "Recommendations",
    "Metacritic score",
    "Categories",
    "Windows",
    "Mac",
    "Linux"
]

clean_df = clean_df[columns_to_keep]

In [87]:
clean_df.head()

,AppID,Name,About the game,Genres,Tags,Developers,Publishers,Price,Release date,Positive,Negative,Recommendations,Metacritic score,Categories,Windows,Mac,Linux
0,2539430,Black Dragon Mage Playtest,NaN,NaN,NaN,NaN,NaN,0.00,"Aug 1, 2023",0,0,0,0,NaN,True,False,False
1,496350,Supipara - Chapter 1 Spring Has Come!,"Springtime, April: when the cherry trees come ...",Adventure,"Adventure,Visual Novel,Anime,Cute",minori,MangaGamer,5.24,"Jul 29, 2016",252,3,231,0,"Single-player,Steam Trading Cards,Steam Cloud,...",True,False,False
2,1034400,Mystery Solitaire The Black Raven,"Immerse yourself in the most beloved, mystical...",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",Somer Games,8floor,4.99,"May 6, 2019",21,3,0,0,"Single-player,Family Sharing",True,True,False
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...","Casual,Indie,Simulation",NaN,유진게임즈,유진게임즈,8.99,"Oct 31, 2024",0,0,0,0,"Single-player,Steam Achievements,Family Sharing",True,False,False
4,3631080,Maze Quest VR,Its not just a Maze; its a Quest! Enter the ca...,"Action,Early Access",NaN,Reality Expanded LLC,Reality Expanded LLC,4.99,"Apr 24, 2025",0,0,0,0,"Single-player,VR Only,Steam Leaderboards,Famil...",True,False,False

In [88]:
text_columns = [
    "About the game",
    "Genres",
    "Tags",
    "Developers",
    "Publishers",
    "Categories"
]

clean_df[text_columns] = clean_df[text_columns].fillna("")

In [89]:
clean_df["Tags"] = clean_df["Tags"].str.replace(",", ", ")
clean_df["Genres"] = clean_df["Genres"].str.replace(",", ", ")
clean_df["Categories"] = clean_df["Categories"].str.replace(",", ", ")

In [90]:
clean_df["embedding_text"] = (
    clean_df["Name"] + ". " +
    clean_df["About the game"] + ". " +
    "Genres: " + clean_df["Genres"] + ". " +
    "Tags: " + clean_df["Tags"] + ". " +
    "Categories: " + clean_df["Categories"]
)

In [91]:
client.delete_collection("steam_games")

True

In [92]:
from qdrant_client.models import Distance, VectorParams

client.create_collection(
    collection_name="steam_games",
    vectors_config=VectorParams(
        size=384,
        distance=Distance.COSINE
    )
)

True

In [93]:
client.get_collections()

CollectionsResponse(collections=[CollectionDescription(name='steam_games')])

In [94]:
sample_df = clean_df.head(10).copy()

vectors = model.encode(
    sample_df["embedding_text"].tolist(),
    show_progress_bar=True
)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [95]:
from qdrant_client.models import PointStruct

points = []

for _, row in sample_df.iterrows():
    payload = {
        "name": row["Name"],
        "genres": row["Genres"],
        "tags": row["Tags"],
        "developers": row["Developers"],
        "publishers": row["Publishers"],
        "price": row["Price"],
        "release_date": row["Release date"],
        "positive": row["Positive"],
        "negative": row["Negative"],
        "categories": row["Categories"],
    }

    points.append(
        PointStruct(
            id=int(row["AppID"]),
            vector=model.encode(row["embedding_text"]).tolist(),
            payload=payload
        )
    )

In [96]:
client.upsert(
    collection_name="steam_games",
    points=points
)

UpdateResult(operation_id=1, status=<UpdateStatus.COMPLETED: 'completed'>)

In [97]:
client.count("steam_games")

CountResult(count=10)

In [99]:
query = "A relaxing card game with puzzles"

query_vector = model.encode(query).tolist()

results = client.query_points(
    collection_name="steam_games",
    query=query_vector,
    limit=5
)

for point in results.points:
    print(point.payload["name"])
    print(point.score)
    print("-" * 50)

Mystery Solitaire The Black Raven
0.6795237
--------------------------------------------------
Maze Quest VR
0.37377355
--------------------------------------------------
Black Dragon Mage Playtest
0.3628258
--------------------------------------------------
MUMBA IV: Egypt Jewels
0.2741236
--------------------------------------------------
Hepta Beats
0.25220755
--------------------------------------------------